import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";

const getJost = Jost({
  variable: "--font-jost",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${getJost.variable} antialiased`}
      >
        <div className="flex items-center justify-center min-h-screen">
          <div className="w-[1200px] h-[1000px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
